version: '3'

# Define services
services:

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      DB_CONNECTION: "root:pass@tcp(0.0.0.0:3306)/"
      DB_NAME: "local_db"
      TEST_DB_NAME: "test_db"
      DB_OPTIONS: "?charset=utf8mb4&parseTime=True&loc=Local"
      PORT: "8080"

    # MYSQL
  mysql:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=local_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
    - 3306:3306